name: user_repository
description: Dart package which manage the user.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  network:
    path: ../network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
