name: authentication_repository
description: Dart package which manage the authentication.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  network:
    path: ../network
  core:
    path: ../core
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
